### ISSUE TITLE
[Development] parsing data

### ISSUE THREAD

**Issue by ANegrash** [season6/crimea-aero#3]
We need to create parsing data functions:
- get JSON data from url https://new.sipaero.ru/json/schedule/ by GET query with parameters: date (yesterday/today/tomorrow), type (departure/arrival/all), lang(ru - default/en)
- parse JSON into objects for LinkedList or another List

**Comment by season6** [comment]
I think it should be a TreeList with its own Comparator sorting by flight status

**Comment by ANegrash** [comment]
Sorting by fly status? Maybe better use time for sorting? And the response data already in this order.
